name: Update Submodules and README

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'  # Ignore README changes to prevent circular triggers
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Update README with external links map
        run: |
          make refresh-readme
          
      - name: Commit README changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README with external links map [ci skip]"
          git push origin main

  deploy-site:
    runs-on: ubuntu-latest
    needs: update-readme
    steps:
      - env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: |
          gh workflow run "Deploy Hugo site to Pages" -R pelicanbaytennisgroups/www